Restaurant search
CS374-On-journey/food-arena-front pull request #68
Opened 2021-05-26 14:58 UTC by haewonc

1. Restaurant Data
visible이랑 search_content 속성이 추가된 것 같아 추가했습니다!

2. Menu Tree
Tree 구조가 되도록 했습니다.

3. Submenu Data
서브메뉴 데이터를 넣었습니다.

4. Party
40개로 늘렸습니다.

2021-05-26 16:31 UTC, gmlwns2000 requested changes

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/index.ts
> +export let managed_ids = new Array<number>(0,1,2,3,4,5,6,7,8,9);
그냥 어래이로 적어도 되지 않나요?

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/index.ts
> +    // managed_ids.push(id)
This may cause unexpected behavior.

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/index.ts
> +    // managed_ids.push(id)
change the code where it called

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/types.ts
> -
I think keep white space look nicer

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +import { PlacesState, IMenu, IPlace, IReview } from './types';
우선 이파일이 너무 긴것 같습니다 패키징을 하면 좋겠습니다

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +      content: "I loved the atmosphere of this restaurant. Also, the food was good.",
리뷰가 좀더 디테일 했으면 좋겠습니다.

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +      author: "Heejun Lee",
이름은 현지인 같은 이름을 채용했으면 좋겠습니다. UT대비

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +        } as IMenu
as IMenu로 캐스팅 함으로써 타이핑에러로 잡아낼수있는 오류를 잡을수 없습니다.

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +        } as IMenu
이런식으로 아까 톡방의 버그가 일어난것 같습니다.

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +var r2 = {
var의 사용은 하지마시고 let을 사용해주시면 좋겠습니다.
var은 스코프가 애매할시 메모리 누수의 위험이 있습니다.

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +  menus :new Array<IMenu>
강제 타이핑은 좋지 않습니다

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +var r2 = {
이 변수를 타이핑 해주십시오

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +      children: new Array<IMenu>(
여기도 마찬가지.
타이핑 에러가 난다면 에러가 나는 원인을 먼저 타이핑 해보는게 좋을것 같습니다.

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +  local_time: `${Math.round(Math.random()*23)+1}:00`,
이건 현지 시간입니다. 현지 시간은 모두 동일한 값을 사용하는게 맞습니다.

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +restaurants.push(r10)
rX 의 값들을 각기 다른 파일로 나누어 index.ts에서 병합하는 방식을 취하는것을 추천합니다.

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/party/party_data.ts
> +  var ret = ""
var의 사용은 자제해주십시오

2021-05-26 16:31 UTC, gmlwns2000 commented on src/store/party/party_data.ts
> +export var parties_data = new Array();
타이핑이 없습니다.

2021-05-26 16:35 UTC, gmlwns2000 commented
메뉴 사진이 대부분 음식이 중앙에 배치되지 않거나 사람이 중심으로 찍혀 보이지 않습니다.

메뉴의 개수가 아직 부족한듯 싶습니다.

메뉴별 사진이 같은 것들이 있습니다.

음식점별 사진이 3장은 적은것 같습니다. 

스크롤의 usability를 확인하기 위해서는 5장은 있어야 할것 같습니다.

2021-05-26 17:53 UTC, haewonc commented on src/store/place/index.ts
> +export let managed_ids = new Array<number>(0,1,2,3,4,5,6,7,8,9);
저게 managed ids가 원래 랜덤 데이터 코드에서는 id를 생성하면서 주는 형식인데, 
제가 만든 restaurants.ts에서는 그냥 차례대로 0~9까지 id를 넣어서 generate_id함수를 쓰지 않아도 돼요
그런데 managed_ids를 다른 파일에서 다 그 이름으로 쓰고 있을테니 generate_id 함수에서 push하는 부분을 주석 처리 하고 
0~9까지 넣었습니다.

아래 리뷰도 똑같은 이유예요!

2021-05-26 17:54 UTC, haewonc commented on src/store/place/types.ts
> -
ok!

2021-05-27 06:11 UTC, haewonc commented on src/store/place/restaurants.ts
> +import { PlacesState, IMenu, IPlace, IReview } from './types';
넵! (차차 수정)

2021-05-27 06:11 UTC, haewonc commented on src/store/place/restaurants.ts
> +      content: "I loved the atmosphere of this restaurant. Also, the food was good.",
넵! (차차 수정)

2021-05-27 06:11 UTC, haewonc commented on src/store/place/restaurants.ts
> +      author: "Heejun Lee",
넵! (차차 수정)

2021-05-27 06:12 UTC, haewonc commented on src/store/place/restaurants.ts
> +        } as IMenu
바꾸겠습니다. (당장 수정)

2021-05-27 06:12 UTC, haewonc commented on src/store/place/restaurants.ts
> +var r2 = {
넵 (당장 수정)

2021-05-27 06:13 UTC, haewonc commented on src/store/place/restaurants.ts
> +  menus :new Array<IMenu>
아하 알겠습니다. (당장 수정)

2021-05-27 06:13 UTC, haewonc commented on src/store/place/restaurants.ts
> +      children: new Array<IMenu>(
아하 알겠습니다. (당장 수정)

2021-05-27 06:13 UTC, haewonc commented on src/store/place/restaurants.ts
> +  local_time: `${Math.round(Math.random()*23)+1}:00`,
알겠습니다. (당장 수정)

2021-05-27 06:14 UTC, haewonc commented on src/store/place/restaurants.ts
> +restaurants.push(r10)
위에 말씀하신 패키징이랑 비슷한 말씀이신거죠? 알겠습니다. (차차 수정)

2021-05-27 06:14 UTC, haewonc commented on src/store/party/party_data.ts
> +  var ret = ""
넵. (당장 수정)

2021-05-27 06:15 UTC, haewonc commented on src/store/party/party_data.ts
> +export var parties_data = new Array();
넵. (당장 수정)

2021-05-27 06:38 UTC, haewonc commented
당장 수정할 것
- 화이트스페이스 
- As IMenu
- src/store/place/restaurants.ts var 대신 let 
- 그리고 as IPlace
- 전체적으로 타입 수정
- 현지 시간 수정
- src/store/party/party_data.ts 11번째 줄 var 사용
- src/store/party/party_data.ts 50번째줄 타이핑

차차 수정할 것
- 레스토랑 데이터 파일 패키징, r1~r10별로 나누기
- 리뷰: 현지인 이름
- 리뷰: 더 디테일하게

으로 나눴습니다. 

당장 수정할 것은 이번 commit으로 다 수정했는데
src/store/party/party_data.ts 50번째줄 타이핑 이거는 여기서 데이터를 가져와서
index.ts에서 let generated_parties = new Array() 이안에 값을 넣어주기 때문에
index.ts의 그 줄을 let generated_parties = new Array<IParty>()로 바꿨어요!

2021-05-30 02:45 UTC, gmlwns2000 requested changes

2021-05-30 02:45 UTC, gmlwns2000 commented on src/store/place/restaurants.ts
> +  local_time: `${22}:00`,
현지시간을 20시정도로 하면 어떨까요?
왠지 이러면 모든 레스토랑이 CLOSED로 나올것 같습니다.
또 몇몇 레스토랑은 20시 이전에 종료하는것으로 하여 CLOSED/OPEN의 차이를 줬으면 합니다

2021-05-30 02:48 UTC, gmlwns2000 commented
![image](https://user-images.githubusercontent.com/4879345/120090370-de7f1100-c13c-11eb-8ea8-32427896a8e8.png)
규카츠집 이미지가 배경이 투명인 문제가 있습니다

2021-06-01 00:56 UTC, merged